// import UserManagement from "../components/usermanagement/Usermanagement";

const ROUTES = {
  LOGIN: "/login",
  Forgotp: "/forgot-password",
  Userregistration: "/user-registration",
  UNAUTHORIZED: "/unauthorized",
  DASHBOARD: "/dashboard",
  UserManagement:"/dashboard/UserManagement",
  Createdprojects:"/dashboard/Createdprojects",
  ProjectDashboard:"/dashboard/ProjectDashboard",
  NPDsheet:"/dashboard/npdsheet",
  MDashboard:"/dashboard/mdashboard",
  MAIN: "/dashboard/main",
  HR: "hr",
  Emanagement: "employeemanagement",
  EmployeeRecord: "employeerecord",
  TeamEvent: "TeamEvent",
  TravelExpense: "TravelExpense",
  // TExpensesForm: "TExpensesForm",
  LeavesAndHoliday : "LeavesAndHoliday",
  TDevlopment : "TDevlopment",
  HolidayUploads : "HolidayUploads",
  Policies : "Policies",  
  // Efeedback : "Efeedback",
  // TrainingDevelopment : "TrainingDevelopment",
  EmployeeFeedback : "EmployeeFeedback",
  AddEmployee: "addemployee",
  MR: "/dashboard/mr",
  DC: "/dashboard/dc",
  Schedule: "/dashboard/schedule",
  MISC: "/dashboard/misc",
  Invoice: "/dashboard/invoice",
  Handover: "/dashboard/handover",
  Sitepics: "/dashboard/sitepics",
  Aftersales: "/dashboard/aftersales",
  NewProject: "/dashboard/newproject",
  Existingproject: "/dashboard/existingproject",
  POCopy: "pocopy",
  PO_SOW: "/dashboard/po_sow",
  Tasks: "/dashboard/tasks",
  PO_SD: "/dashboard/po_sd",
  POForm: "/dashboard/poform",
  TC: "/dashboard/tc",
  PRForm: "/dashboard/prform",
  Workorder: "/dashboard/workorder",
  Sitelayout: "/dashboard/sitelayout",
  POA: "/dashboard/poa",

};

export default ROUTES;